code --install-extension alexr00.formatallfilesinworkspace
code --install-extension Angular.ng-template
code --install-extension batisteo.vscode-django
code --install-extension christian-kohler.npm-intellisense
code --install-extension dbaeumer.vscode-eslint
code --install-extension donjayamanne.python-environment-manager
code --install-extension donjayamanne.python-extension-pack
code --install-extension dracula-theme.theme-dracula
code --install-extension eamodio.gitlens
code --install-extension eg2.vscode-npm-script
code --install-extension equinusocio.vsc-material-theme-icons
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension formulahendry.code-runner
code --install-extension humao.rest-client
code --install-extension idered.npm
code --install-extension jasonnutter.search-node-modules
code --install-extension KevinRose.vsc-python-indent
code --install-extension mechatroner.rainbow-csv
code --install-extension mhutchie.git-graph
code --install-extension MS-CEINTL.vscode-language-pack-pt-BR
code --install-extension ms-python.isort
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension naumovs.color-highlight
code --install-extension njpwerner.autodocstring
code --install-extension PKief.material-icon-theme
code --install-extension RandomFractalsInc.vscode-data-preview
code --install-extension redhat.java
code --install-extension redhat.vscode-xml
code --install-extension ritwickdey.LiveServer
code --install-extension sibiraj-s.vscode-scss-formatter
code --install-extension steoates.autoimport
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension streetsidesoftware.code-spell-checker-portuguese
code --install-extension sygene.auto-correct
code --install-extension syler.sass-indented
code --install-extension usernamehw.errorlens
code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
code --install-extension VisualStudioExptTeam.vscodeintellicode
code --install-extension vscjava.vscode-java-debug
code --install-extension vscjava.vscode-java-dependency
code --install-extension vscjava.vscode-java-pack
code --install-extension vscjava.vscode-maven
code --install-extension wholroyd.jinja
